# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emokit.ui'
#
# Created: Wed Dec 11 19:42:16 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 776)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gl_quality = QtGui.QGridLayout()
        self.gl_quality.setObjectName("gl_quality")
        self.verticalLayout.addLayout(self.gl_quality)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.pBdisconnect = QtGui.QPushButton(self.centralwidget)
        self.pBdisconnect.setObjectName("pBdisconnect")
        self.verticalLayout.addWidget(self.pBdisconnect)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lEdev = QtGui.QLineEdit(self.centralwidget)
        self.lEdev.setMinimumSize(QtCore.QSize(149, 0))
        self.lEdev.setMaxLength(50)
        self.lEdev.setCursorPosition(12)
        self.lEdev.setObjectName("lEdev")
        self.verticalLayout.addWidget(self.lEdev)
        self.pBconnect = QtGui.QPushButton(self.centralwidget)
        self.pBconnect.setObjectName("pBconnect")
        self.verticalLayout.addWidget(self.pBconnect)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gl_sens = QtGui.QGridLayout()
        self.gl_sens.setObjectName("gl_sens")
        self.gridLayout.addLayout(self.gl_sens, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_OpenSetup = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OpenSetup.setIcon(icon)
        self.action_OpenSetup.setObjectName("action_OpenSetup")
        self.action_SaveSetup = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SaveSetup.setIcon(icon1)
        self.action_SaveSetup.setObjectName("action_SaveSetup")
        self.action_OpenConnection = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/page_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OpenConnection.setIcon(icon2)
        self.action_OpenConnection.setObjectName("action_OpenConnection")
        self.action_CloseConnection = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CloseConnection.setIcon(icon3)
        self.action_CloseConnection.setObjectName("action_CloseConnection")
        self.actionQuality = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/weather_lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuality.setIcon(icon4)
        self.actionQuality.setObjectName("actionQuality")
        self.menu_File.addAction(self.action_OpenSetup)
        self.menu_File.addAction(self.action_SaveSetup)
        self.menubar.addAction(self.menu_File.menuAction())
        self.toolBar.addAction(self.action_OpenSetup)
        self.toolBar.addAction(self.action_SaveSetup)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_OpenConnection)
        self.toolBar.addAction(self.action_CloseConnection)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuality)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyqt epoc by hpl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Battery: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pBdisconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Device: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lEdev.setText(QtGui.QApplication.translate("MainWindow", "/dev/hidraw4", None, QtGui.QApplication.UnicodeUTF8))
        self.pBconnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_OpenSetup.setText(QtGui.QApplication.translate("MainWindow", "&OpenSetup", None, QtGui.QApplication.UnicodeUTF8))
        self.action_SaveSetup.setText(QtGui.QApplication.translate("MainWindow", "&SaveSetup", None, QtGui.QApplication.UnicodeUTF8))
        self.action_OpenConnection.setText(QtGui.QApplication.translate("MainWindow", "&OpenConnection", None, QtGui.QApplication.UnicodeUTF8))
        self.action_CloseConnection.setText(QtGui.QApplication.translate("MainWindow", "&CloseConnection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuality.setText(QtGui.QApplication.translate("MainWindow", "quality", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuality.setToolTip(QtGui.QApplication.translate("MainWindow", "show sensor quality", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

